name: Static Checks

on:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Static Checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install modules
              run: yarn
            - name: Lint
              run: yarn lint-nofix
            - name: Prettier
              run: yarn prettier-nofix
            - name: Knip
              run: yarn knip
